nil subclass: #Object
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''.

Object subclass: #Behavior
	instanceVariableNames: 'name instanceSpec methods superclass variables classVariables poolDictionaries category'
	classVariableNames: ''
	poolDictionaries: ''.

Behavior subclass: #Class
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''.

Behavior subclass: #Metaclass
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''.

Object subclass: #Block
	instanceVariableNames: 'context argCount argLoc bytePointer'
	classVariableNames: ''
	poolDictionaries; ''.
