SRCS = stx.c memory.c object.c symbol.c class.c \
	hash.c misc.c context.c token.c parser.c bootstrp.c
OBJS = stx.obj memory.obj object.obj symbol.obj class.obj \
	hash.obj misc.obj context.obj token.obj parser.obj bootstrp.obj
OUT = xpstx.lib

CC = lcc
CFLAGS = -I../..  -A -ansic -libcdll 
LDFLAGS =
LIBS = 

all: $(OBJS)
	lcclib $(OUT) $(OBJS) 

clean:
	del $(OBJS) $(OUT) *.obj

.SUFFIXES: .c .obj
.c.obj:
	$(CC) $(CFLAGS) -c $<
