SRCS = \
	stx.c memory.c object.c symbol.c class.c \
	hash.c misc.c context.c token.c parser.c bootstrp.c
OBJS = $(SRCS:.c=.obj)
OUT = xpstx.lib

CC = bcc32
CFLAGS = -O2 -WM -w -w-inl -w-sig -w-spa -w-hid -RT- -I../..

all: $(OBJS)
	tlib $(OUT) @&&!
+-$(**: = &^
+-)
!

clean:
	del $(OBJS) $(OUT) *.obj

.SUFFIXES: .c .obj
.c.obj:
	$(CC) $(CFLAGS) -c $<

