SRCS = stx.c memory.c object.c symbol.c class.c array.c \
	dict.c misc.c name.c token.c parser.c bootstrp.c \
	bytecode.c interp.c
OBJS = stx.obj memory.obj object.obj symbol.obj class.obj array.obj \
	dict.obj misc.obj name.obj token.obj parser.obj bootstrp.obj \
	bytecode.obj interp.obj
OUT = xpstx.lib

CC = lcc
CFLAGS = -I../..  -A -ansic #-libcdll 
LDFLAGS =
LIBS = 

all: $(OBJS)
	lcclib $(OUT) $(OBJS) 

clean:
	del $(OBJS) $(OUT) *.obj

.SUFFIXES: .c .obj
.c.obj:
	$(CC) $(CFLAGS) -c $<
