/*
 * $Id: Exception.java 183 2008-06-03 08:18:55Z baconevi $
 *
 * {License}
 */

package ase.awk;

public class Exception extends java.lang.Exception
{
	private int code;
	private int line;

	// generated by generrcode-java.awk
	public static final int NOERR = 0;
	public static final int CUSTOM = 1;
	public static final int INVAL = 2;
	public static final int NOMEM = 3;
	public static final int NOSUP = 4;
	public static final int NOPER = 5;
	public static final int NODEV = 6;
	public static final int NOSPC = 7;
	public static final int MFILE = 8;
	public static final int MLINK = 9;
	public static final int AGAIN = 10;
	public static final int NOENT = 11;
	public static final int EXIST = 12;
	public static final int FTBIG = 13;
	public static final int TBUSY = 14;
	public static final int ISDIR = 15;
	public static final int IOERR = 16;
	public static final int OPEN = 17;
	public static final int READ = 18;
	public static final int WRITE = 19;
	public static final int CLOSE = 20;
	public static final int INTERN = 21;
	public static final int RUNTIME = 22;
	public static final int BLKNST = 23;
	public static final int EXPRNST = 24;
	public static final int SINOP = 25;
	public static final int SINCL = 26;
	public static final int SINRD = 27;
	public static final int SOUTOP = 28;
	public static final int SOUTCL = 29;
	public static final int SOUTWR = 30;
	public static final int LXCHR = 31;
	public static final int LXDIG = 32;
	public static final int LXUNG = 33;
	public static final int ENDSRC = 34;
	public static final int ENDCMT = 35;
	public static final int ENDSTR = 36;
	public static final int ENDREX = 37;
	public static final int LBRACE = 38;
	public static final int LPAREN = 39;
	public static final int RPAREN = 40;
	public static final int RBRACK = 41;
	public static final int COMMA = 42;
	public static final int SCOLON = 43;
	public static final int COLON = 44;
	public static final int STMEND = 45;
	public static final int IN = 46;
	public static final int NOTVAR = 47;
	public static final int EXPRES = 48;
	public static final int FUNC = 49;
	public static final int WHILE = 50;
	public static final int ASSIGN = 51;
	public static final int IDENT = 52;
	public static final int FNNAME = 53;
	public static final int BLKBEG = 54;
	public static final int BLKEND = 55;
	public static final int DUPBEG = 56;
	public static final int DUPEND = 57;
	public static final int BFNRED = 58;
	public static final int AFNRED = 59;
	public static final int GBLRED = 60;
	public static final int PARRED = 61;
	public static final int DUPPAR = 62;
	public static final int DUPGBL = 63;
	public static final int DUPLCL = 64;
	public static final int BADPAR = 65;
	public static final int BADVAR = 66;
	public static final int UNDEF = 67;
	public static final int LVALUE = 68;
	public static final int GBLTM = 69;
	public static final int LCLTM = 70;
	public static final int PARTM = 71;
	public static final int DELETE = 72;
	public static final int RESET = 73;
	public static final int BREAK = 74;
	public static final int CONTINUE = 75;
	public static final int NEXTBEG = 76;
	public static final int NEXTEND = 77;
	public static final int NEXTFBEG = 78;
	public static final int NEXTFEND = 79;
	public static final int PRINTFARG = 80;
	public static final int PREPST = 81;
	public static final int GLNCPS = 82;
	public static final int DIVBY0 = 83;
	public static final int OPERAND = 84;
	public static final int POSIDX = 85;
	public static final int ARGTF = 86;
	public static final int ARGTM = 87;
	public static final int FNNONE = 88;
	public static final int NOTIDX = 89;
	public static final int NOTDEL = 90;
	public static final int NOTMAP = 91;
	public static final int NOTMAPIN = 92;
	public static final int NOTMAPNILIN = 93;
	public static final int NOTREF = 94;
	public static final int NOTASS = 95;
	public static final int IDXVALASSMAP = 96;
	public static final int POSVALASSMAP = 97;
	public static final int MAPTOSCALAR = 98;
	public static final int SCALARTOMAP = 99;
	public static final int MAPNOTALLOWED = 100;
	public static final int VALTYPE = 101;
	public static final int RDELETE = 102;
	public static final int RRESET = 103;
	public static final int RNEXTBEG = 104;
	public static final int RNEXTEND = 105;
	public static final int RNEXTFBEG = 106;
	public static final int RNEXTFEND = 107;
	public static final int BFNUSER = 108;
	public static final int BFNIMPL = 109;
	public static final int IOUSER = 110;
	public static final int IONONE = 111;
	public static final int IOIMPL = 112;
	public static final int IONMEM = 113;
	public static final int IONMNL = 114;
	public static final int FMTARG = 115;
	public static final int FMTCNV = 116;
	public static final int CONVFMTCHR = 117;
	public static final int OFMTCHR = 118;
	public static final int REXRECUR = 119;
	public static final int REXRPAREN = 120;
	public static final int REXRBRACKET = 121;
	public static final int REXRBRACE = 122;
	public static final int REXUNBALPAR = 123;
	public static final int REXCOLON = 124;
	public static final int REXCRANGE = 125;
	public static final int REXCCLASS = 126;
	public static final int REXBRANGE = 127;
	public static final int REXEND = 128;
	public static final int REXGARBAGE = 129;
	// end of error codes

	public Exception () 
	{
		super ();
		this.code = NOERR;
		this.line = 0;
	}

	public Exception (String msg)
	{
		super (msg);
		this.code = CUSTOM;
		this.line = 0;
	}

	public Exception (String msg, int code)
	{
		super (msg);
		this.code = code;
		this.line = 0;
	}

	public Exception (String msg, int code, int line)
	{
		super (msg);
		this.code = code;
		this.line = line;
	}

	public int getCode ()
	{
		return this.code;
	}

	public int getLine ()
	{
		return this.line;
	}
}
