CC = lcc
CFLAGS = -I../../.. -A -ansic -libcdll 
#LDFLAGS = -L../../../xp/bas -L../../../xp/stx
#LIBS = -lxpstx -lxpbas
LDFLAGS = -subsystem console -dynamic -s
LIBS = ..\..\..\xp\bas\xpbas.lib ..\..\..\xp\stx\xpstx.lib

all: stx parser

stx: stx.obj
	lcclnk $(LDFLAGS) -o stx.exe stx.obj $(LIBS)

parser: parser.obj
	lcclnk $(LDFLAGS) -o parser.exe parser.obj $(LIBS)


clean:
	del $(OBJS) *.obj $(OUT)

.SUFFIXES: .c .obj
.c.obj:
	$(CC) $(CFLAGS) -c $< 

