CC = bcc32
CFLAGS = -I..\..\..
LDFLAGS = -L..\..\..\xp\bas -L..\..\..\xp\stx
LIBS = import32.lib cw32mt.lib xpbas.lib xpstx.lib
STARTUP = c0x32w.obj

all: stx parser

stx: stx.obj
	ilink32 $(LDFLAGS) $(STARTUP) stx.obj,stx.exe,,$(LIBS),,

parser: parser.obj
	ilink32 $(LDFLAGS) $(STARTUP) parser.obj,parser.exe,,$(LIBS),,

clean:
	del $(OBJS) *.obj $(OUT)

.SUFFIXES: .c .obj
.c.obj:
	$(CC) $(CFLAGS) -c $< 

