SRCS = stx.c
OBJS = stx.obj
OUT = stx.exe

CC = bcc32
CFLAGS = -I..\..\..
LDFLAGS = -L..\..\..\xp\bas -L..\..\..\xp\stx
LIBS = import32.lib cw32mt.lib xpbas.lib xpstx.lib
STARTUP = c0x32w.obj

all: $(OBJS)
	ilink32 $(LDFLAGS) $(STARTUP) $(OBJS),$(OUT),,$(LIBS),,

clean:
	del $(OBJS) *.obj $(OUT)

.SUFFIXES: .c .obj
.c.obj:
	$(CC) $(CFLAGS) -c $< 

