SRCS = stx.c
OBJS = stx.obj
OUT = stx.exe

CC = lcc
CFLAGS = -I../../.. -A -ansic -libcdll 
#LDFLAGS = -L../../../xp/bas -L../../../xp/stx
#LIBS = -lxpstx -lxpbas
LDFLAGS = -subsystem console -dynamic
LIBS = ..\..\..\xp\bas\xpbas.lib ..\..\..\xp\stx\xpstx.lib

all: $(OBJS)
	lcclnk $(LDFLAGS) -o $(OUT) $(OBJS) $(LIBS)

clean:
	del $(OBJS) *.obj $(OUT)

.SUFFIXES: .c .obj
.c.obj:
	$(CC) $(CFLAGS) -c $< 

