"isNil" "test if self is nil"
perform: method with: x with: y with: z with: a1 with: b2 with: c2

	| a b c d e f g |

	< primitive: 16 >
"
	a := 'this is ''good'.
	a := #xxx niceMethod.
"
	b := 12345 xxx nil this.
	b := 30 + 20.
	b := 'zzzzzz' xxx: 'cccccc' xy zzzz: 30 ccc:10 ccc: 'cccccc'.
	$3 asString.
	$4 asString.
	$4 asString.
	$5 asString.
	$5 asString.

	selector := 20.
"
	(jjj xxx: 10 xy) zzz: (10 fuck: 20 you: 40) yyy:  kkk.
	[ spec plus:  20].
	^10."
