SRCS = name.c token.c array.c prim.c mem.c env.c init.c read.c eval.c print.c
OBJS = name.obj token.obj array.obj prim.obj mem.obj env.obj init.obj read.obj eval.obj print.obj
OUT = sselsp.lib

CC = lcc
CFLAGS = -I../..  -A -ansic -libcdll 
LDFLAGS =
LIBS = 

all: $(OBJS)
	lcclib $(OUT) $(OBJS) 

clean:
	del $(OBJS) $(OUT) *.obj

.SUFFIXES: .c .obj
.c.obj:
	$(CC) $(CFLAGS) -c $<
