/*
 * $Id: Exception.java,v 1.6 2007/10/10 07:03:56 bacon Exp $
 *
 * {License}
 */

package ase.awk;

public class Exception extends java.lang.Exception
{
	private int code;
	private int line;

	// generated by generrcode-java.awk
	public static final int NOERR = 0;
	public static final int INVAL = 1;
	public static final int NOMEM = 2;
	public static final int NOSUP = 3;
	public static final int NOPER = 4;
	public static final int NODEV = 5;
	public static final int NOSPC = 6;
	public static final int MFILE = 7;
	public static final int MLINK = 8;
	public static final int AGAIN = 9;
	public static final int NOENT = 10;
	public static final int EXIST = 11;
	public static final int FTBIG = 12;
	public static final int TBUSY = 13;
	public static final int ISDIR = 14;
	public static final int IOERR = 15;
	public static final int OPEN = 16;
	public static final int READ = 17;
	public static final int WRITE = 18;
	public static final int CLOSE = 19;
	public static final int INTERN = 20;
	public static final int RUNTIME = 21;
	public static final int BLKNST = 22;
	public static final int EXPRNST = 23;
	public static final int SINOP = 24;
	public static final int SINCL = 25;
	public static final int SINRD = 26;
	public static final int SOUTOP = 27;
	public static final int SOUTCL = 28;
	public static final int SOUTWR = 29;
	public static final int LXCHR = 30;
	public static final int LXDIG = 31;
	public static final int LXUNG = 32;
	public static final int ENDSRC = 33;
	public static final int ENDCMT = 34;
	public static final int ENDSTR = 35;
	public static final int ENDREX = 36;
	public static final int LBRACE = 37;
	public static final int LPAREN = 38;
	public static final int RPAREN = 39;
	public static final int RBRACK = 40;
	public static final int COMMA = 41;
	public static final int SCOLON = 42;
	public static final int COLON = 43;
	public static final int STMEND = 44;
	public static final int IN = 45;
	public static final int NOTVAR = 46;
	public static final int EXPRES = 47;
	public static final int FUNC = 48;
	public static final int WHILE = 49;
	public static final int ASSIGN = 50;
	public static final int IDENT = 51;
	public static final int FNNAME = 52;
	public static final int BLKBEG = 53;
	public static final int BLKEND = 54;
	public static final int DUPBEG = 55;
	public static final int DUPEND = 56;
	public static final int BFNRED = 57;
	public static final int AFNRED = 58;
	public static final int GBLRED = 59;
	public static final int PARRED = 60;
	public static final int DUPPAR = 61;
	public static final int DUPGBL = 62;
	public static final int DUPLCL = 63;
	public static final int BADPAR = 64;
	public static final int BADVAR = 65;
	public static final int UNDEF = 66;
	public static final int LVALUE = 67;
	public static final int GBLTM = 68;
	public static final int LCLTM = 69;
	public static final int PARTM = 70;
	public static final int DELETE = 71;
	public static final int RESET = 72;
	public static final int BREAK = 73;
	public static final int CONTINUE = 74;
	public static final int NEXTBEG = 75;
	public static final int NEXTEND = 76;
	public static final int NEXTFBEG = 77;
	public static final int NEXTFEND = 78;
	public static final int PRINTFARG = 79;
	public static final int PREPST = 80;
	public static final int GLNCPS = 81;
	public static final int DIVBY0 = 82;
	public static final int OPERAND = 83;
	public static final int POSIDX = 84;
	public static final int ARGTF = 85;
	public static final int ARGTM = 86;
	public static final int FNNONE = 87;
	public static final int NOTIDX = 88;
	public static final int NOTDEL = 89;
	public static final int NOTMAP = 90;
	public static final int NOTMAPIN = 91;
	public static final int NOTMAPNILIN = 92;
	public static final int NOTREF = 93;
	public static final int NOTASS = 94;
	public static final int IDXVALASSMAP = 95;
	public static final int POSVALASSMAP = 96;
	public static final int MAPTOSCALAR = 97;
	public static final int SCALARTOMAP = 98;
	public static final int MAPNOTALLOWED = 99;
	public static final int VALTYPE = 100;
	public static final int RDELETE = 101;
	public static final int RRESET = 102;
	public static final int RNEXTBEG = 103;
	public static final int RNEXTEND = 104;
	public static final int RNEXTFBEG = 105;
	public static final int RNEXTFEND = 106;
	public static final int BFNUSER = 107;
	public static final int BFNIMPL = 108;
	public static final int IOUSER = 109;
	public static final int IONONE = 110;
	public static final int IOIMPL = 111;
	public static final int IONMEM = 112;
	public static final int IONMNL = 113;
	public static final int FMTARG = 114;
	public static final int FMTCNV = 115;
	public static final int CONVFMTCHR = 116;
	public static final int OFMTCHR = 117;
	public static final int REXRECUR = 118;
	public static final int REXRPAREN = 119;
	public static final int REXRBRACKET = 120;
	public static final int REXRBRACE = 121;
	public static final int REXUNBALPAR = 122;
	public static final int REXCOLON = 123;
	public static final int REXCRANGE = 124;
	public static final int REXCCLASS = 125;
	public static final int REXBRANGE = 126;
	public static final int REXEND = 127;
	public static final int REXGARBAGE = 128;
	// end of error codes

	public Exception () 
	{
		super ();
		this.code = NOERR;
		this.line = 0;
	}

	public Exception (String msg)
	{
		super (msg);
		this.code = NOERR;
		this.line = 0;
	}

	public Exception (String msg, int code)
	{
		super (msg);
		this.code = code;
		this.line = 0;
	}

	public Exception (String msg, int code, int line)
	{
		super (msg);
		this.code = code;
		this.line = line;
	}

	public int getCode ()
	{
		return this.code;
	}

	public int getLine ()
	{
		return this.line;
	}
}
