/*
 * $Id: Exception.java,v 1.4 2007/06/25 14:13:23 bacon Exp $
 *
 * {License}
 */

package ase.awk;

public class Exception extends java.lang.Exception
{
	private int code;
	private int line;

	// generated by generrcode-java.awk
	public static final int NOERR = 0;
	public static final int INVAL = 1;
	public static final int NOMEM = 2;
	public static final int NOSUP = 3;
	public static final int NOPER = 4;
	public static final int NODEV = 5;
	public static final int NOSPC = 6;
	public static final int MFILE = 7;
	public static final int MLINK = 8;
	public static final int AGAIN = 9;
	public static final int NOENT = 10;
	public static final int EXIST = 11;
	public static final int FTBIG = 12;
	public static final int TBUSY = 13;
	public static final int ISDIR = 14;
	public static final int IOERR = 15;
	public static final int OPEN = 16;
	public static final int READ = 17;
	public static final int WRITE = 18;
	public static final int CLOSE = 19;
	public static final int INTERN = 20;
	public static final int RUNTIME = 21;
	public static final int BLKNST = 22;
	public static final int EXPRNST = 23;
	public static final int SINOP = 24;
	public static final int SINCL = 25;
	public static final int SINRD = 26;
	public static final int SOUTOP = 27;
	public static final int SOUTCL = 28;
	public static final int SOUTWR = 29;
	public static final int LXCHR = 30;
	public static final int LXUNG = 31;
	public static final int ENDSRC = 32;
	public static final int ENDCMT = 33;
	public static final int ENDSTR = 34;
	public static final int ENDREX = 35;
	public static final int LBRACE = 36;
	public static final int LPAREN = 37;
	public static final int RPAREN = 38;
	public static final int RBRACK = 39;
	public static final int COMMA = 40;
	public static final int SCOLON = 41;
	public static final int COLON = 42;
	public static final int STMEND = 43;
	public static final int IN = 44;
	public static final int NOTVAR = 45;
	public static final int EXPRES = 46;
	public static final int WHILE = 47;
	public static final int ASSIGN = 48;
	public static final int IDENT = 49;
	public static final int FNNAME = 50;
	public static final int BLKBEG = 51;
	public static final int BLKEND = 52;
	public static final int DUPBEG = 53;
	public static final int DUPEND = 54;
	public static final int BFNRED = 55;
	public static final int AFNRED = 56;
	public static final int GBLRED = 57;
	public static final int PARRED = 58;
	public static final int DUPPAR = 59;
	public static final int DUPGBL = 60;
	public static final int DUPLCL = 61;
	public static final int BADPAR = 62;
	public static final int BADVAR = 63;
	public static final int UNDEF = 64;
	public static final int LVALUE = 65;
	public static final int GBLTM = 66;
	public static final int LCLTM = 67;
	public static final int PARTM = 68;
	public static final int DELETE = 69;
	public static final int BREAK = 70;
	public static final int CONTINUE = 71;
	public static final int NEXTBEG = 72;
	public static final int NEXTEND = 73;
	public static final int NEXTFBEG = 74;
	public static final int NEXTFEND = 75;
	public static final int PRINTFARG = 76;
	public static final int PREPST = 77;
	public static final int GLNCPS = 78;
	public static final int DIVBY0 = 79;
	public static final int OPERAND = 80;
	public static final int POSIDX = 81;
	public static final int ARGTF = 82;
	public static final int ARGTM = 83;
	public static final int FNNONE = 84;
	public static final int NOTIDX = 85;
	public static final int NOTDEL = 86;
	public static final int NOTMAP = 87;
	public static final int NOTMAPIN = 88;
	public static final int NOTMAPNILIN = 89;
	public static final int NOTREF = 90;
	public static final int NOTASS = 91;
	public static final int IDXVALASSMAP = 92;
	public static final int POSVALASSMAP = 93;
	public static final int MAPTOSCALAR = 94;
	public static final int SCALARTOMAP = 95;
	public static final int MAPNOTALLOWED = 96;
	public static final int VALTYPE = 97;
	public static final int RDELETE = 98;
	public static final int RNEXTBEG = 99;
	public static final int RNEXTEND = 100;
	public static final int RNEXTFBEG = 101;
	public static final int RNEXTFEND = 102;
	public static final int BFNUSER = 103;
	public static final int BFNIMPL = 104;
	public static final int IOUSER = 105;
	public static final int IONONE = 106;
	public static final int IOIMPL = 107;
	public static final int IONMEM = 108;
	public static final int IONMNL = 109;
	public static final int FMTARG = 110;
	public static final int FMTCNV = 111;
	public static final int CONVFMTCHR = 112;
	public static final int OFMTCHR = 113;
	public static final int REXRECUR = 114;
	public static final int REXRPAREN = 115;
	public static final int REXRBRACKET = 116;
	public static final int REXRBRACE = 117;
	public static final int REXUNBALPAR = 118;
	public static final int REXCOLON = 119;
	public static final int REXCRANGE = 120;
	public static final int REXCCLASS = 121;
	public static final int REXBRANGE = 122;
	public static final int REXEND = 123;
	public static final int REXGARBAGE = 124;
	// end of error codes

	public Exception () 
	{
		super ();
		this.code = NOERR;
		this.line = 0;
	}

	public Exception (String msg)
	{
		super (msg);
		this.code = NOERR;
		this.line = 0;
	}

	public Exception (String msg, int code)
	{
		super (msg);
		this.code = code;
		this.line = 0;
	}

	public Exception (String msg, int code, int line)
	{
		super (msg);
		this.code = code;
		this.line = line;
	}

	public int getCode ()
	{
		return this.code;
	}

	public int getLine ()
	{
		return this.line;
	}
}
