SRCS = awk.c tree.c tab.c map.c parse.c run.c sa.c 
OBJS = awk.obj tree.obj tab.obj map.obj parse.obj run.obj sa.obj 
OUT = xpawk.lib

CC = lcc
CFLAGS = -I../..  -A -ansic -libcdll  -D__STAND_ALONE
LDFLAGS =
LIBS = 

all: $(OBJS)
	lcclib /verbose $(OUT) $(OBJS) 

clean:
	del $(OBJS) $(OUT) *.obj

.SUFFIXES: .c .obj
.c.obj:
	$(CC) $(CFLAGS) -c $<
