SRCS = \
	awk.c err.c tree.c str.c tab.c map.c parse.c \
	run.c rec.c val.c func.c misc.c extio.c rex.c
OBJS = $(SRCS:.c=.o)
OUT = libaseawk.a

CC = gcc
#CFLAGS = -m64 -O2 -Wall -std=c89 -pedantic -I../.. 
CFLAGS = -m64 -O2 -Wall -I../.. 

all: $(OBJS)
	ar cr $(OUT) $(OBJS)

clean:
	rm -rf $(OBJS) $(OUT) *.obj

.SUFFIXES: .c .o
.c.o:
	$(CC) $(CFLAGS) -c $<

