SRCS = awk.c err.c tree.c tab.c map.c parse.c run.c sa.c val.c misc.c
OBJS = awk.obj err.obj tree.obj tab.obj map.obj parse.obj run.obj sa.obj val.obj misc.obj
OUT = xpawk.lib

CC = lcc
CFLAGS = -I../..  -A -ansic -libcdll  -DXP_AWK_STAND_ALONE
LDFLAGS =
LIBS = 

all: $(OBJS)
	lcclib /verbose $(OUT) $(OBJS) 

clean:
	del $(OBJS) $(OUT) *.obj

.SUFFIXES: .c .obj
.c.obj:
	$(CC) $(CFLAGS) -c $<
