CC = lcc
CFLAGS = -I../../.. -A -ansic -libcdll 
#LDFLAGS = -subsystem console -dynamic -s
LDFLAGS = -subsystem console -s -L../../../xp/bas -L../../../xp/awk
LIBS = xpbas.lib xpawk.lib

all: awk 

awk: awk.obj
	lcclnk $(LDFLAGS) -o awk.exe awk.obj $(LIBS)

clean:
	del $(OBJS) *.obj $(OUT)

.SUFFIXES: .c .obj
.c.obj:
	$(CC) $(CFLAGS) -c $< 

