CC = bcc32
LD = ilink32
CFLAGS = -O2 -WM -WU -RT- -w -I..\..\.. 
LDFLAGS = -ap -L..\..\awk -L"c:\program files\borland\bds\4.0\lib"
LIBS = import32.lib cw32mt.lib aseawk.lib
STARTUP = c0x32w.obj

all: awk 

awk: awk.obj
	$(LD) $(LDFLAGS) $(STARTUP) awk.obj,awk.exe,,$(LIBS),,

clean:
	del $(OBJS) *.obj $(OUT)

.SUFFIXES: .c .obj
.c.obj:
	$(CC) $(CFLAGS) -c $< 

