
# ilink32.exe     link.exe
# -aa             /subsystem:windows
# -ap             /subsystem:console
# -ad             /subsystem:native
#
# -Tpe            
# -Tpd            /dll

CC = bcc32
LD = ilink32
CFLAGS = -O2 -WM -WU -RT- -w -I..\..\.. 
LDFLAGS = -ap -Tpe -Gn -c -L..\..\awk -L"c:\program files\borland\bds\4.0\lib"
LIBS = import32.lib cw32mt.lib aseawk.lib
STARTUP = c0x32w.obj

all: awk 

awk: awk.obj
	$(LD) $(LDFLAGS) $(STARTUP) awk.obj,$@.exe,,$(LIBS),,

java: 
	javac -classpath ../../.. Awk.java AwkApplet.java

jrun:
	java -Xms1m -Xmx2m -classpath ../../.. ase.test.awk.Awk 

clean:
	del $(OBJS) *.obj *.class awk.exe 

.SUFFIXES: .c .obj
.c.obj:
	$(CC) $(CFLAGS) -c $< 

