CC = gcc
CFLAGS = -m64 -Wall -O2 -I../../.. -D__STAND_ALONE
LDFLAGS = -m64 -L../../bas -L../../awk
LIBS = -lxpawk -lm

all: awk

awk: awk.o
	$(CC) -o awk awk.o $(LDFLAGS) $(LIBS)

clean:
	rm -f *.o awk

.SUFFIXES: .c .o
.c.o:
	$(CC) -c $(CFLAGS) $< 

